export const GET_SOURCES_REQUEST = '/sources/GET_SOURCES_REQUEST';
export const GET_SOURCES_SUCCESS = '/sources/GET_SOURCES_SUCCESS';
export const GET_SOURCES_FAILURE = '/sources/GET_SOURCES_FAILURE';
export const GET_DISABLED_SOURCES = '/sources/GET_DISABLED_SOURCES';
export const TOGGLE_DISABLED_SOURCE = '/sources/TOGGLE_DISABLE_SOURCE';
export const ADD_DISABLED_SOURCES = '/sources/ADD_DISABLED_SOURCES';
export const REMOVE_DISABLED_SOURCES = '/sources/REMOVE_DISABLED_SOURCES';
export const CLEAR_DISABLED_SOURCES = '/source/CLEAR_DISABLED_SOURCES';